In [1]:
import numpy as np

In [2]:
person1=[8.5,34,123,54]

In [3]:
mode=["happy","sad","peaceful","suprised","mizerable"]

In [5]:
weights=np.random.randn(4,5)

In [6]:
weights

array([[ 0.10402946, -1.34583763, -0.71339706,  0.03338134, -0.78211908],
       [-0.13385333,  0.53504099,  1.92412706,  0.83202108,  0.98039805],
       [ 0.08680329, -0.47180962, -0.70345433,  0.06475442, -3.51928611],
       [-0.55934931, -1.20150577, -0.00542327,  0.06876916, -0.68493179]])

In [7]:
np.dot(person1,weights)

array([ -23.1948204 , -116.16212065,  -27.46129398,   40.25078601,
       -443.17298644])

In [10]:
bias=np.random.randn(1,5)

In [11]:
bias

array([[0.90720667, 0.57389917, 0.51732751, 0.31773344, 0.49504095]])

In [13]:
logits=np.dot(person1,weights)+bias

In [23]:
logits

array([[ -22.28761372, -115.58822149,  -26.94396648,   40.56851945,
        -442.67794549]])

In [24]:
def softmax(x):
#     x=x-np.max(x)
    print(x)
    return np.exp(x)/np.sum(np.exp(x))

In [25]:
softmax(logits)

[[ -22.28761372 -115.58822149  -26.94396648   40.56851945 -442.67794549]]


array([[5.03417385e-028, 1.52050936e-068, 4.78299473e-030,
        1.00000000e+000, 1.34501423e-210]])

In [37]:
y_about_person=[0 ,1,0,0]

In [38]:
predicated=[0.04,0.7,0.2,0.06]

In [39]:
def cross_entropy(label,predicated):
    return -sum(label[i]*np.log(predicated[i]) for i in range(len(label)))

In [40]:
cross_entropy(y_about_person,predicated)

0.35667494393873245